### ISSUE TITLE
Text instead of Bitmaps 

### ISSUE THREAD

**Issue by NikoBoerger** [imaNNeoFighT/ArcChartView#6]
Hi,
thanks so much for your library. It really helps me out. 
I will create a dart board with it to show the hit quotas for the different targets around the board. However, as you see in the Screenshots, I need to show numbers instead of bitmap icons around the chart. Could you add a simple feature to add texts instead of bitmaps?

Thanks a lot,
Niko

![Screenshot_20201220-232656_Dart Pro Training Sheet](https://user-images.githubusercontent.com/8778527/102726092-1b3c1600-431c-11eb-8264-35d49b7d1746.jpg)

**Comment by imaNNeo** [comment]
Hi. I don't maintain this library anymore.
